-- Script Date: 10/16/2017 13:56  - ErikEJ.SqlCeScripting version 3.5.2.72

--drop table AdvertSites;

CREATE TABLE IF NOT EXISTS  [AdvertSites] (
  [Id] INTEGER PRIMARY KEY AUTOINCREMENT
, [Name] VARCHAR(200) NOT NULL
, [Url] VARCHAR(200) NOT NULL
, [UrlRo] VARCHAR(200) NULL
, [UrlRu] VARCHAR(200) NULL
);

--drop table Category;

CREATE TABLE IF NOT EXISTS  [Category] (
  [Id] INTEGER PRIMARY KEY AUTOINCREMENT
, [Url] VARCHAR(100) NOT NULL
, [SiteUrl] VARCHAR(100) NOT NULL
, [NameRo] VARCHAR(100) NOT NULL
, [NameRu] VARCHAR(100) NOT NULL
);

--drop table SubCategory;

CREATE TABLE IF NOT EXISTS  [SubCategory] (
  [Id] INTEGER PRIMARY KEY AUTOINCREMENT
, [Url] VARCHAR(100) NOT NULL
, [CategoryUrl] VARCHAR(100) NOT NULL
, [NameRo] VARCHAR(100) NOT NULL
, [NameRu] VARCHAR(100) NOT NULL
);
